controller_joint_names: ['', 'left_shoulder_pitch_rs04', 'left_shoulder_roll_rs04', 'left_shoulder_yaw_rs03', 'left_elbow_rs03', 'left_wrist_rs02', 'left_hand_rs02', 'left_palm_right_finger', 'left_palm_left_finger', ]
