controller_joint_names: ['', 'left_shoulder_pitch_rs04_joint', 'left_shoulder_roll_rs04_joint', 'left_shoulder_yaw_rs03_joint', 'left_elbow_rs03_joint', 'left_wrist_rs02_joint', 'left_hand_rs02_joint', ]
